Features/connect user api
371team4/371Team4 pull request #123
Opened 2018-03-21 20:55 UTC by benkorol

added modules for login and user apis

/src/store/modules/user/index.js
getAllUsers
createUser
updateUser
deleteUser

/src/store/modules/login/index.js
signIn

## Description

## Related Issue or Trello Card

[Trello card](https://trello.com/c/qZMWLHOl/2-connect-the-rest-apis-to-the-front-end)

## Motivation and Context

to not use firebase
## How Has This Been Tested?

- [ ] Unit test
- [ ] NightWatch test
- [ ] Coverage testing
- [ ] Manual testing

## Test Cases and test paths

unit test for signIn and getAllUsers
## Screenshots (if appropriate):

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-03-21 23:44 UTC, MoranLi requested changes
might need unit test for create user and update user
might need action delete user

2018-03-24 15:43 UTC, KingMackle commented
Sorry about not doing the reviews. I am looking into [moxios](https://github.com/axios/moxios) atm so we don't need to rely on the server to be present

2018-03-27 03:02 UTC, KingMackle approved these changes

2018-03-27 17:41 UTC, Masonfrith approved these changes

2018-03-27 18:30 UTC, ert485 commented
>MoranLi requested changes 6 days ago
>>might need unit test for create user and update user
>>might need action delete user

Updates on this? It looks like these were added

2018-03-27 18:31 UTC, ert485 approved these changes

2018-03-27 18:38 UTC, MoranLi approved these changes

2018-03-29 02:38 UTC, merged